syntax on

set shell=/bin/bash
set shiftwidth=4
set tabstop=4
set expandtab
set textwidth=0
set autoindent
set hlsearch
set clipboard=unnamed
set number relativenumber
set ruler
set scrolloff=5
set backspace=indent,eol,start
set directory=$HOME/.vim/swap//
set viminfo+=n~/.vim/viminfo
set wildmenu

let mapleader = "\<space>"
