alias g='git'
alias mx='tmuxinator'
alias ff='fzf'
alias ls='ls -F --color=auto'
alias la='ls -A'
alias ll='la -l'
alias cd='z'
alias ttyd-dev='ttyd -W -p 7681 -t fontSize=24 -t cursorStyle=bar tmux new -A -s dev'
